# Generated by Django 3.2.20 on 2023-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
