# Generated by Django 3.2.20 on 2023-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_song_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='like_count',
            field=models.PositiveBigIntegerField(),
        ),
    ]
