# Generated by Django 3.2.20 on 2023-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20231001_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(help_text='add tags', through='catalog.SongTag', to='catalog.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Enter a song tags', max_length=200),
        ),
    ]
